### ISSUE TITLE
Consider adding a more helpful error message when contracts `.csproj` includes domain stuff

### ISSUE THREAD

**Issue by bartekpacia** [leancodepl/contractsgenerator-dart#44]
Possible symptoms of the problem:
```
$ dart run contracts_generator
Null check operator used on a null value
#0      GeneratorDatabase._isKind (package:contracts_generator/src/generator_database.dart:125:33)
#1      GeneratorDatabase.isAttribute.<anonymous closure> (package:contracts_generator/src/generator_database.dart:144:18)
#2      ListMixin.any (dart:collection/list.dart:149:15)
#3      PbListBase.any (package:protobuf/src/protobuf/pb_list.dart:220:59)
#4      GeneratorDatabase.isAttribute (package:contracts_generator/src/generator_database.dart:143:48)
#5      ContractsGenerator.generate (package:contracts_generator/src/contracts_generator.dart:88:53)
<asynchronous suspension>
#6      ContractsGenerator.toCode (package:contracts_generator/src/contracts_generator.dart:123:8)
<asynchronous suspension>
#7      ContractsGenerator.writeAll (package:contracts_generator/src/contracts_generator.dart:134:30)
<asynchronous suspension>
#8      main (file:///Users/bartek/.pub-cache/hosted/pub.dartlang.org/contracts_generator-0.4.3/bin/contracts_generator.dart:30:7)
<asynchronous suspension>

An unknown error occurred, this is most likely a bug. Please consider reporting it with the above error.
```

How @shilangyu helped me fix it: 
we went through `**/*.Contracts.csproj` files in project's `backend` folder and found a rogue `<ProjectReference Include="../ProjectName.Core.Domain/ProjectName.Core.Domain.csproj" />` in `<ItemGroup>`. It was unused, so simply removing it fixed the mobile contracts generator.

**Comment by jakubfijalkowski** [comment]
DM me the project (plus commit that still has the problem) please, I'm wondering how the backend part behaves. In theory, it should reject this first.
